"use client";

import { useState } from "react";
import { useRouter } from "next/navigation";
import { Banknote, LockKeyhole, Plus, Wallet } from "lucide-react";

import { AppShell } from "@/components/layout/AppShell";
import { Button } from "@/components/ui/button";

interface ShiftData { id: string; status: "OPEN" | "CLOSED"; openingCash: number; expectedCash: number; actualCash: number | null; cashVariance: number | null; openedAt: string; closedAt: string | null; orders: Array<{ id: string; totalAmount: number; paymentMethod: string | null; completedAt: string | null }>; cashMovements: Array<{ id: string; type: string; amount: number; reason: string; createdAt: string }> }
const money = (value: number) => new Intl.NumberFormat("th-TH", { style: "currency", currency: "THB" }).format(value);
const inputClass = "h-14 w-full rounded-xl border border-slate-200 px-4 text-lg font-bold outline-none focus:border-slate-950";

export function ShiftManager({ initialShift }: { initialShift: ShiftData | null }) {
  const router = useRouter(); const [openingCash, setOpeningCash] = useState(1000); const [actualCash, setActualCash] = useState(initialShift?.expectedCash ?? 0); const [amount, setAmount] = useState(0); const [reason, setReason] = useState(""); const [error, setError] = useState(""); const [saving, setSaving] = useState(false);
  const cashSales = initialShift?.orders.filter((order) => order.paymentMethod === "CASH").reduce((sum, order) => sum + order.totalAmount, 0) ?? 0;
  const perform = async (body: object) => { setSaving(true); setError(""); const response = await fetch("/api/shifts", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify(body) }); const result = await response.json() as { error?: string }; if (!response.ok) setError(result.error || "ดำเนินการไม่สำเร็จ"); else router.refresh(); setSaving(false); };
  if (!initialShift || initialShift.status === "CLOSED") return <AppShell title="กะและเงินสด" description="เปิดกะก่อนเริ่มขายเพื่อกระทบยอดเงินสดปลายวัน"><div className="mx-auto mt-12 max-w-lg rounded-3xl border bg-white p-8 text-center shadow-sm"><div className="mx-auto flex size-16 items-center justify-center rounded-2xl bg-amber-100"><Wallet className="size-8 text-amber-700" /></div><h2 className="mt-5 text-2xl font-black">เปิดกะใหม่</h2>{initialShift && <p className="mt-2 text-sm text-slate-500">กะก่อนหน้าต่างกัน {money(initialShift.cashVariance ?? 0)}</p>}<label className="mt-7 block text-left text-sm font-bold">เงินสดตั้งต้น<input type="number" min="0" value={openingCash} onChange={(e) => setOpeningCash(Number(e.target.value))} className={`${inputClass} mt-2 text-right`} /></label>{error && <p className="mt-3 text-sm font-bold text-rose-600">{error}</p>}<Button disabled={saving} onClick={() => perform({ action: "OPEN", openingCash })} className="mt-5 h-14 w-full rounded-xl text-base font-black">เปิดกะ</Button></div></AppShell>;
  return <AppShell title="กะและเงินสด" description="กระทบยอดเงินสด เงินเข้าออก และปิดกะ"><div className="grid gap-4 sm:grid-cols-3"><article className="rounded-3xl bg-slate-950 p-6 text-white"><Banknote className="size-7 text-amber-400" /><p className="mt-4 text-sm text-slate-400">เงินที่ควรมีในลิ้นชัก</p><p className="mt-1 text-3xl font-black">{money(initialShift.expectedCash)}</p></article><article className="rounded-3xl border bg-white p-6"><p className="text-sm text-slate-500">ยอดเงินสดจากการขาย</p><p className="mt-2 text-3xl font-black">{money(cashSales)}</p></article><article className="rounded-3xl border bg-white p-6"><p className="text-sm text-slate-500">จำนวนบิลในกะ</p><p className="mt-2 text-3xl font-black">{initialShift.orders.length}</p></article></div>
  <div className="mt-6 grid gap-6 lg:grid-cols-2"><section className="rounded-3xl border bg-white p-6"><h2 className="text-lg font-black">นำเงินเข้า / นำเงินออก</h2><div className="mt-4 grid grid-cols-[1fr_2fr] gap-3"><input type="number" min="0" value={amount || ""} onChange={(e) => setAmount(Number(e.target.value))} placeholder="จำนวนเงิน" className={inputClass} /><input value={reason} onChange={(e) => setReason(e.target.value)} placeholder="เหตุผล เช่น ซื้อของด่วน" className={inputClass} /></div><div className="mt-3 grid grid-cols-2 gap-3"><Button variant="outline" disabled={saving} onClick={() => perform({ action: "MOVEMENT", type: "CASH_IN", amount, reason })} className="h-14 rounded-xl font-bold"><Plus className="size-5" />เงินเข้า</Button><Button variant="outline" disabled={saving} onClick={() => perform({ action: "MOVEMENT", type: "CASH_OUT", amount, reason })} className="h-14 rounded-xl font-bold">− เงินออก</Button></div><div className="mt-5 divide-y">{initialShift.cashMovements.map((movement) => <div key={movement.id} className="flex justify-between py-3 text-sm"><div><b>{movement.reason}</b><p className="text-xs text-slate-400">{new Date(movement.createdAt).toLocaleString("th-TH")}</p></div><b className={movement.type === "CASH_IN" ? "text-emerald-600" : "text-rose-600"}>{movement.type === "CASH_IN" ? "+" : "-"}{money(movement.amount)}</b></div>)}</div></section>
  <section className="rounded-3xl border bg-white p-6"><LockKeyhole className="size-7" /><h2 className="mt-3 text-lg font-black">ปิดกะและนับเงินจริง</h2><p className="mt-1 text-sm leading-6 text-slate-500">นับเงินสดทั้งหมดในลิ้นชัก ระบบจะคำนวณเงินขาด/เกินให้อัตโนมัติ</p><label className="mt-5 block text-sm font-bold">เงินสดที่นับได้<input type="number" min="0" value={actualCash || ""} onChange={(e) => setActualCash(Number(e.target.value))} className={`${inputClass} mt-2 text-right`} /></label><div className="mt-4 flex justify-between rounded-xl bg-slate-50 p-4"><span>ผลต่างเบื้องต้น</span><b className={actualCash - initialShift.expectedCash < 0 ? "text-rose-600" : "text-emerald-600"}>{money(actualCash - initialShift.expectedCash)}</b></div><Button disabled={saving} onClick={() => perform({ action: "CLOSE", actualCash })} className="mt-4 h-14 w-full rounded-xl bg-rose-600 font-black hover:bg-rose-700">ยืนยันปิดกะ</Button></section></div>{error && <p className="mt-5 rounded-xl bg-rose-50 p-4 font-bold text-rose-700">{error}</p>}</AppShell>;
}
